# Site settings
title: Booze
email: bronxbombers242@gmail.com
description: >
  Browns fan blog  
  
baseurl: ""
url: "http://BrandonLee24.github.io"
twitter_username: BrandonLee24
github_username: BrandonLee24

# Build settings
markdown: kramdown
