# Site settings
title: Browns Fan 
description: Cleveland Browns Loyalist Blogger
author: Brandon Lee
baseurl: ""
url: "https://BrandonLee24.github.io"
#paginate: 5 

# Social
facebook: profile.php?id=100004072487134
twitter: BrandonLee24
github: BrandonLee24

permalink: /:title
include: ['_pages']

# Google Analytics
analytics_id: "UA-117146766-1"

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

#plugins:
#  - jekyll-paginate

exclude:
  - README.md
  - LICENSE
